<a href="https://colab.research.google.com/github/ravi-prakash1907/Problem-Solving-with-Python/blob/main/Class%20Notebooks/Lab%2010.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lec 10

## Files & Exception



### Files
1. Read Mode (r)  
2. Write Mode (w  and  a+)  
3. Read-Write Mode ()  

_Keeping a track:_  
1. seek()
2. tell()

Text and Binary file are most oftenly used 

In [ ]:
myFile = open("info.txt", "w") # formats if info.txt exists
myFile.writelines("I am great.\n")
myFile.close()

In [ ]:
myFile = open("info.txt", "r") # opens to read only
text = myFile.readlines()
myFile.close()

print(text)

['I am great.\n']


**Write without formating**

In [ ]:
myFile = open("info.txt", "a+") # formats if info.txt exists
myFile.writelines("You know, I'm Ravi!!\n")
myFile.close()

myFile = open("info.txt", "r") # opens to read only
text = myFile.readlines()
myFile.close()

print(text)

['I am great.\n', "You know, I'm Ravi!!\n"]


#### seek()

In [ ]:
myFile = open("info.txt", "r") # opens to read only
text = myFile.readline()
pos = len(text)
myFile.close()


# using seek to read only 2nd line
myFile = open("info.txt", "r") # opens to read only
myFile.seek(pos)
text = myFile.readline()
myFile.close()


print(text)

You know, I'm Ravi!!



In [ ]:
myFile = open("info.txt", "r") # opens to read only

for text in myFile.readlines():
  print(text)
myFile.close()

I am great.

You know, I'm Ravi!!



#### tell()

_Gives the current position of the curser._  
_(how many charectors are read)_

In [ ]:
myFile = open("info.txt", "r") # opens to read only
text = myFile.readline()
myFile.seek(myFile.tell() + 4)  # skips init 4 charectors in 2nd line
myFile.close()


#### Writing using **print()**

In [ ]:
myFile = open("info.dat", "w") # opens to write only

a = 1.0
b = "this"
c = [12,-4]
print(a,b,c,file=myFile)
myFile.close()

In [ ]:
## copying

myFile1 = open("info.txt", "r") # opens to write only
myFile2 = open("fileout.txt", "w") # opens to write only

myFile1.readline()

for line in myFile1:
  myFile2.write(line)


myFile1.close()
myFile2.close()

**Writing multiple lines**

In [ ]:
data = ["People are very emotional.\n",
        "Still, they do not help others!\n"]

myFile = open("info.txt", "w") # formats if info.txt exists
myFile.writelines(data)
myFile.close()

## Exceptions

As **python** is an object oriented lang., so **exceptions** are also the _objects_  

These are defined in **exceptions** module of python  


### Few common exceptions:

1. ImportError (module not found)  
2. IndexError (index out of range)  
3. NameError (identifier not found)  
4. TypeError (passed different datatype)  
5. ValueError (int + str)  
6. IOError (file not found)  

In [ ]:
print([1,2,3][3])  # IndexError

IndexError: ignored

In [ ]:
print(2 + '3') # TypeError

TypeError: ignored

In [ ]:
print(Lsst[0]) # NameError

NameError: ignored

In [ ]:
print(int('12.5')) # ValueError

ValueError: ignored

### Exception Hendling

# Lab 10

Introduced modules:  
1. NumPy
2. Pandas

## NumPy

Attributes Introduced  
* ndim
* shape
* dtype

Functoions Introduced:  
* array()  
* sum()  
* arange()
* linspace()
* abs()
* reshap()
* mul()


In [ ]:
import numpy as np

**List Addition vs NumPy Addition**

In [ ]:
l1 = [1,2,3,4]
l2 = [1,2,3,4]

print(l1+l2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])

print(arr1+arr2)

[ 2  4  6  8 10]


**Other Operations**

In [ ]:
arr1.ndim

1

In [ ]:
arr1.shape

(5,)

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr3 = np.array(['a', 'b'])
arr3.dtype

dtype('<U1')

In [ ]:
arr3 = np.array([1.2, 34, 54.67])
arr3.dtype

dtype('float64')

In [ ]:
arr3 = np.array([99, 'b'])
arr3.dtype

dtype('<U21')

In [ ]:
arr4 = np.array(['1','2','3'], dtype='int')
print(arr4)
arr4.dtype

[1 2 3]


dtype('int64')

In [ ]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
arr5 = np.arange(10)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr6 = arr5.reshape(5,2)
arr6

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
## devide an interval inequal parts
arr7 = np.linspace(1,30,6)
arr7

array([ 1. ,  6.8, 12.6, 18.4, 24.2, 30. ])

In [ ]:
arr7[:4]

array([ 1. ,  6.8, 12.6, 18.4])

In [ ]:
## access multiple elements
arr7[[2,3]]

array([12.6, 18.4])

In [ ]:
arr8 = np.array([list(range(1,6)),
                list(range(6,11)),
                list(range(11,16)),
                list(range(16,21)),
                list(range(21,26))])

arr8[3]

array([16, 17, 18, 19, 20])

In [ ]:
print(arr8[3,])  # row 4
print(arr8[2,4]) # elem in row3, col5
print(arr8[:,2])  # col 3

[16 17 18 19 20]
15
[ 3  8 13 18 23]


In [ ]:
arr8[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [ ]:
arr8[[1,2],3]

array([ 9, 14])

In [ ]:
# sum of elements
arr8.sum()

325

In [ ]:
np.sum(arr8)

325

In [ ]:
np.mean(arr8).round(2)

13.0

In [ ]:
np.median(arr8)

13.0

In [ ]:
# row/colwise
np.mean(arr8, axis=1).round(2)  # row-wise

array([ 3.,  8., 13., 18., 23.])

In [ ]:
np.mean(arr8, 0).round(2)  # col-wise

array([11., 12., 13., 14., 15.])

In [ ]:
## changing values
arr9 = np.array([list(range(1,6)),
                list(range(6,11)),
                list(range(11,16)),
                list(range(16,21)),
                list(range(21,26))])

arr9[:,3] = 50
arr9[4,] *= -1
arr9

array([[  1,   2,   3,  50,   5],
       [  6,   7,   8,  50,  10],
       [ 11,  12,  13,  50,  15],
       [ 16,  17,  18,  50,  20],
       [-21, -22, -23, -50, -25]])

In [ ]:
np.abs(arr9)

array([[ 1,  2,  3, 50,  5],
       [ 6,  7,  8, 50, 10],
       [11, 12, 13, 50, 15],
       [16, 17, 18, 50, 20],
       [21, 22, 23, 50, 25]])

In [ ]:
x0 = np.zeros((2,6))
x0

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
x1 = np.ones((2,6))
x1

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
identityMat = np.eye(4,5)
identityMat

identityMat = np.eye(4,4)
identityMat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Matrix Mul**

In [ ]:
A = np.arange(8).reshape(2,4)
B = np.arange(8).reshape(4,2)

C = A.dot(B)
C

array([[28, 34],
       [76, 98]])

Transpose **T**

In [ ]:
D = np.arange(10).reshape(2,5)
D.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## Pandas

Functions Introduced:  
1. Series()
2. DataFrame()
3. head()
4. tail()

Others:  
1. dtype
2. shape

In [ ]:
import pandas as pd


In [ ]:
s1 = pd.Series([1,2,3,5,6])
s1

0    1
1    2
2    3
3    5
4    6
dtype: int64

In [ ]:
## format index
s2 = pd.Series([1,-2,3,-4,5],index=['a', 'b', 'c', 'd', 'e'])
s2

a    1
b   -2
c    3
d   -4
e    5
dtype: int64

In [ ]:
s2['d']

-4

In [ ]:
s2[['a',"c"]]

a    1
c    3
dtype: int64

**Boolean Indexing**

In [ ]:
exp = s2 > 0
print(s2[exp])

s3 = s2

s3.index = exp
s3

a    1
c    3
e    5
dtype: int64


True     1
False   -2
True     3
False   -4
True     5
dtype: int64

In [ ]:
myDiction = {'year':[2000,2001,2002],
              'state':['UP','Delhi','Haryana'],
              'pop':[213,578,9834]}

df1 = pd.DataFrame(myDiction)
df1

year    state   pop
0  2000       UP   213
1  2001    Delhi   578
2  2002  Haryana  9834

In [ ]:
df1['avg'] = df1['pop']/sum(df1['pop'])
df1

year    state   pop       avg
0  2000       UP   213  0.020047
1  2001    Delhi   578  0.054400
2  2002  Haryana  9834  0.925553

In [ ]:
del df1['avg']
df1

year    state   pop
0  2000       UP   213
1  2001    Delhi   578
2  2002  Haryana  9834

In [ ]:
temp = df1['year']
print(df1.drop(0))
df1

   year    state   pop
1  2001    Delhi   578
2  2002  Haryana  9834


year    state   pop
0  2000       UP   213
1  2001    Delhi   578
2  2002  Haryana  9834

In [ ]:
temp = df1['year']
print(df1.drop(0,inplace=True))
df1

None


year    state   pop
1  2001    Delhi   578
2  2002  Haryana  9834

In [ ]:
df = pd.read_csv('covidDeaths.csv')
df.head()

word  freq
0   china   444
1   italy   280
2    iran   266
3   spain   243
4  france   242

In [ ]:
df.shape

(161, 2)